name: ActionsTest

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode for the build'
        required: true
        default: 'dev-ts'
      version:
        description: 'Version for the build'
        required: true
        default: '1.0.0'
      brand:
        description: 'Brand for the build'
        required: true
        default: 'anywhere.app'
      OS: 
        type: choice
        description: 'OS for the build'
        required: true
        options: 
            - macos-latest
            - windows-latest
jobs:
 live:
   runs-on: ${{ github.event.inputs.OS }}
               
   steps: 
              
      - name: Enter Input Values.
        run: |
            echo "Mode: ${{ github.event.inputs.mode }}"
            echo "Version: ${{ github.event.inputs.version }}"
            echo "Brand: ${{ github.event.inputs.brand }}"
            echo "OS: ${{ github.event.inputs.OS }}"
              

